spring:
  application:
    name: draw-lots
  messages:
    basename: i18n/messages
    fallbackToSystemLocale: true
  flyway:
    enabled: ${FLYWAY_ENABLED}
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        logSlowQueries: true
        maintainTimeStats: false
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        rewriteBatchedStatements: true
        useServerPrepStmts: true
        useLocalSessionState: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
logging:
  level:
    root: ${ROOT_LOGGING_LEVEL}
    web: ${WEB_LOGGING_LEVEL}
management:
  endpoints:
    web:
      exposure:
        include: '*'